# Name your project! Project names should contain only lowercase characters
# and underscores.
name: 'retail_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'retail_dbt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_dbt:

    staging:
      +schema: retail_staging
      +materialized: view

    marts:
      +schema: retail_marts
      +materialized: table